// <auto-generated />
using ASP.Net6Repository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.Net6Repository.Migrations
{
    [DbContext(typeof(RepoDbContext))]
    partial class RepoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ASP.Net6Repository.Models.Repository", b =>
                {
                    b.Property<int>("SathyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SathyaId"), 1L, 1);

                    b.Property<string>("SathyaLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SathyaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SathyaId");

                    b.ToTable("repositorys");
                });
#pragma warning restore 612, 618
        }
    }
}
